# name: Playwright Tests

# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]

# jobs:
#   docker:
#     name: 'Build Docker Image'
#     runs-on: ubuntu-latest
#     needs: playwright
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Build Docker image
#         run: docker build -t playwright-tests:latest .

#       # Optionally, push the image to Docker Hub or another registry
#       - name: Push Docker image
#         run: |
#           echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#           docker tag playwright-tests:latest iamarra/playwright-tests:latest
#           docker push iamarra/playwright-tests:latest
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#   playwright:
#     name: 'Playwright Tests'
#     runs-on: ubuntu-latest
#     container:
#       image: mcr.microsoft.com/playwright:v1.40.0-jammy
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm ci

#       - name: Run your tests
#         run: npx playwright test
#         env:
#           HOME: /root
#           USERNAME: ${{ secrets.USERNAME }}
#           PASSWORD: ${{ secrets.PASSWORD }}

name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright-docker:
    name: 'Build Docker Image and Run Playwright Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t playwright-tests:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push iamarra/playwright-tests:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Playwright tests
        run: |
          docker run --rm -e USERNAME="${{ secrets.USERNAME }}" -e PASSWORD="${{ secrets.PASSWORD }}" playwright-tests:latest
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
